{ "type": "suite", "event": "started", "test_count": "4" }
{ "type": "test", "event": "started", "name": "f::a" }
{ "type": "test", "name": "f::a", "event": "ok" }
{ "type": "test", "event": "started", "name": "f::b" }
{ "type": "test", "name": "f::b", "event": "failed", "stdout": "thread 'f::b' panicked at 'assertion failed: false', f.rs:18:5\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.\n" }
{ "type": "test", "event": "started", "name": "f::c" }
{ "type": "test", "name": "f::c", "event": "ok" }
{ "type": "test", "event": "started", "name": "f::d" }
{ "type": "test", "name": "f::d", "event": "ignored" }
{ "type": "suite", "event": "failed", "passed": 2, "failed": 1, "allowed_fail": 0, "ignored": 1, "measured": 0, "filtered_out": "0" }
